### ISSUE TITLE
No module named music_163

### ISSUE THREAD

**Issue by FrankHan** [RitterHou/music-163#1]
你好，我是爬虫的初学者，下载了你的源码，直接F5了 artists.py，显示：
`from music_163 import sql
ImportError: No module named music_163`
请教下这个是什么原因？

我是python 2.7.13 on win32.

**Comment by RitterHou** [comment]
你好，这里是因为我本来这个文件是在 music_163 这个包下执行的，而且在当前文件中引入了同样在这个包下的 sql.py 中的内容，所以如果你直接执行的话会导致无法找到 sql.py 这样的错误。

解释大概就是这样，如果还有什么不了解的，建议详细的了解一下 Python 的包管理机制。

**Comment by FrankHan** [comment]
好的，明白了，谢谢！
