### ISSUE TITLE
第21行的引号

### ISSUE THREAD

**Issue by FrankHan** [RitterHou/music-163#2]
music_by_album.py
 第21行 ：  R'eferer' 似乎应该是  'Referer'

**Comment by RitterHou** [comment]
抱歉，没明白什么意思，具体指的是哪个文件中的第21行？

**Comment by FrankHan** [comment]
music_by_album.py 刚才忘了写了，不好意思

**Comment by RitterHou** [comment]
你好，我发现问题了，谢谢指出☺

**Comment by FrankHan** [comment]
你好，我想顺便请教一下，如何获取网易云音乐一个用户的听歌排行列表？比如用户：
http://music.163.com/#/user/home?id=102072323
的听歌排行页面是：
http://music.163.com/#/user/songs/rank?id=102072323
我F12了一下，发现这个排行页面，调用的是：
Request URL:http://music.163.com/weapi/v1/play/record?csrf_token=BLABLA
这个调用没有用户的id信息，这是为什么呢？

**Comment by RitterHou** [comment]
id 应该是以某种方式进行了加密之后保存在了 `params` 或者 `encSecKey` 中

**Comment by FrankHan** [comment]
果然哎！
我直接在页面F12了一下，把params 和encSecKey拷贝了进代码，果然获得了这个用户的听歌列表。
可是怎么能知道到底是怎么加密的呢？ >_<

**Comment by RitterHou** [comment]
应该是通过 JS 对 ID 进行了加密，这个应该只能分析网页源码来获取加密方式了，或者在网上搜索一下看有没有人已经研究出来这种加密算法是什么了。~~或者给网易云的程序员打个电话问一下也行。~~

**Comment by FrankHan** [comment]
好的 >_<
